In [1]:
# =============================================================================
# Assignment One
# =============================================================================

import numpy as np

zero_arr = np.zeros((4,3,2), dtype=float)
print(zero_arr)

ones_arr = np.ones((2,3,4), dtype=float)
print(ones_arr)

square_arr = np.arange(1,50).reshape(7,7)
print(square_arr)

list_arr = np.array([3, 8, 1.2, -3, 4.24, 9, 10])
print(list_arr)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42]
 [43 44 45 46 47 48 49]]
[ 3.    8.    1.2  -3.    4.24  9.   10.  ]


In [2]:
# =============================================================================
# Assignment Two
# =============================================================================

print(list_arr[1])

print(list_arr[1:5])

center_arr = square_arr[2:5, 2:5]
print(center_arr)

even_arr = square_arr[::2, ::2]
print(even_arr)

8.0
[ 8.    1.2  -3.    4.24]
[[17 18 19]
 [24 25 26]
 [31 32 33]]
[[ 1  3  5  7]
 [15 17 19 21]
 [29 31 33 35]
 [43 45 47 49]]


In [3]:
# =============================================================================
# Assignment Three
# =============================================================================

five_arr = np.zeros((5,5), dtype=int) + 5
five_arr[1:4, 1:4] = 0
print(five_arr)

[[5 5 5 5 5]
 [5 0 0 0 5]
 [5 0 0 0 5]
 [5 0 0 0 5]
 [5 5 5 5 5]]


In [4]:
# =============================================================================
# Assignment Four
# =============================================================================

three_arr = np.zeros((3,3), dtype=int) + 3 + np.arange(1,4)
n = int(input("Enter an integer n: "))
n_arr = np.zeros((n,n), dtype=int) + n + np.arange(1,n+1)
print(three_arr)
print(n_arr)

print(np.sum(three_arr), np.sum(n_arr))

[[4 5 6]
 [4 5 6]
 [4 5 6]]
[[ 6  7  8  9 10]
 [ 6  7  8  9 10]
 [ 6  7  8  9 10]
 [ 6  7  8  9 10]
 [ 6  7  8  9 10]]
45 200


In [5]:
# =============================================================================
# Assignment Five
# =============================================================================

five_arr[1:4, 1:4] = three_arr
print(five_arr)

print(np.concatenate((center_arr, three_arr), axis=0))
print(np.concatenate((center_arr, three_arr), axis=0).reshape(2,3,3))
print(np.concatenate((center_arr, three_arr), axis=1).reshape(3,2,3))

[[5 5 5 5 5]
 [5 4 5 6 5]
 [5 4 5 6 5]
 [5 4 5 6 5]
 [5 5 5 5 5]]
[[17 18 19]
 [24 25 26]
 [31 32 33]
 [ 4  5  6]
 [ 4  5  6]
 [ 4  5  6]]
[[[17 18 19]
  [24 25 26]
  [31 32 33]]

 [[ 4  5  6]
  [ 4  5  6]
  [ 4  5  6]]]
[[[17 18 19]
  [ 4  5  6]]

 [[24 25 26]
  [ 4  5  6]]

 [[31 32 33]
  [ 4  5  6]]]
